import React from 'react';
import { X, Maximize2, Minimize2 } from 'lucide-react';
import { FloorPlanData } from '@/types/floor-plan';
import { FloorPlanRenderer } from './FloorPlanRenderer';
import { motion, AnimatePresence } from 'framer-motion';

interface FloorPlanModalProps {
    isOpen: boolean;
    onClose: () => void;
    data?: FloorPlanData;
    imageUrl?: string; // The storyboard image used for reference
}

export function FloorPlanModal({ isOpen, onClose, data, imageUrl }: FloorPlanModalProps) {
    if (!isOpen || !data) return null;

    return (
        <AnimatePresence>
            <motion.div
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                className="fixed inset-0 z-[100] flex items-center justify-center bg-black/80 backdrop-blur-sm p-4"
                onClick={onClose}
            >
                <motion.div
                    initial={{ scale: 0.95, opacity: 0 }}
                    animate={{ scale: 1, opacity: 1 }}
                    exit={{ scale: 0.95, opacity: 0 }}
                    onClick={(e) => e.stopPropagation()}
                    className="bg-[#0f172a] border border-[#334155] rounded-xl shadow-2xl w-full max-w-6xl h-[90vh] flex flex-col overflow-hidden"
                >
                    {/* Header */}
                    <div className="flex justify-between items-center p-4 border-b border-[#334155]">
                        <h2 className="text-lg font-bold text-white flex items-center gap-2">
                            <span className="bg-blue-600 w-2 h-6 rounded-sm"></span>
                            Schematic Floor Plan Analysis
                        </h2>
                        <button
                            onClick={onClose}
                            className="p-2 hover:bg-white/10 rounded-full transition-colors text-gray-400 hover:text-white"
                        >
                            <X className="w-5 h-5" />
                        </button>
                    </div>

                    {/* Content */}
                    <div className="flex-1 flex overflow-hidden">

                        {/* Left: Source Image (Reference) */}
                        {imageUrl && (
                            <div className="w-1/3 bg-black border-r border-[#334155] p-4 flex flex-col gap-2">
                                <h3 className="text-xs font-bold text-gray-500 uppercase tracking-widest">Source Reference</h3>
                                <div className="relative aspect-video rounded-lg overflow-hidden border border-[#334155]">
                                    <img
                                        src={imageUrl}
                                        alt="Source"
                                        className="w-full h-full object-contain"
                                    />
                                </div>
                                <div className="mt-4 p-3 bg-blue-900/20 border border-blue-500/30 rounded text-xs text-blue-200 leading-relaxed">
                                    <strong className="block text-blue-400 mb-1">AI Analysis Context</strong>
                                    The diagram on the right is generated by analyzing spatial cues from this storyboard sketch, focusing on physical boundaries, character placement, and camera angle.
                                </div>
                            </div>
                        )}

                        {/* Right: The Floor Plan (Zoomable Area) */}
                        <div className={`relative flex-1 bg-[#f0f0f0] flex items-center justify-center p-8 ${!imageUrl ? 'w-full' : ''}`}>
                            <div className="w-full h-full shadow-lg bg-white">
                                <FloorPlanRenderer data={data} />
                            </div>
                        </div>

                    </div>
                </motion.div>
            </motion.div>
        </AnimatePresence>
    );
}
